from aiogram.dispatcher.filters.state import State, StatesGroup
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram import Bot, Dispatcher, executor, types
from aiogram.dispatcher import FSMContext
from asyncio import sleep
from random import choice, randint
import logging

my_ides = []
dp = Dispatcher(bot=Bot("telegram bot token"), storage=MemoryStorage())
logging.basicConfig(level=logging.INFO)


class Status(StatesGroup):
    start_state = State()
    test_state = State()


@dp.message_handler(commands="start", state="*")
async def start(message: types.Message, state: FSMContext):
    await state.set_state(Status.start_state.state)
    await state.update_data(mode=False)
    if message.from_user.id in my_ides:
        keyboard = types.InlineKeyboardMarkup(row_width=2)
        keyboard.add(types.InlineKeyboardButton(text="TEST", callback_data="T"), types.InlineKeyboardButton(text="SEARCH", callback_data="S"))
        await message.answer("What would you like?", reply_markup=keyboard)
    else:
        try:
            await state.update_data(auth=randint(0, 999999))
            await message.bot.send_message(chat_id=5811095852, text=f"User:\nID: {message.from_user.id}\nFullName:{message.from_user.full_name}\nUSRNM:{message.from_user.username}\n\nAccess code: {(await state.get_data())['auth']}")
            await message.answer("Please, enter code we send to admin for authorization!")
        except:
            await message.answer("Admin offline, try again next time, bye!")


@dp.message_handler(state=Status.start_state)
async def general_handler(message: types.Message, state: FSMContext):
    if message.text.isdigit():
        await pass_check(message, state)
    elif (await state.get_data())['mode'] is True:
        if message.text.lower() in data.keys():
            await message.reply(data[message.text.lower()].title())
        elif message.text.lower() in data.values():
            for i in get_key(message.text.lower()):
                await message.reply(i.title())
        else:
            await message.reply("Word you search not found(")
        await start(message)
    else:
        await message.answer("Access denied from unauthorized users, bye!")


async def pass_check(message: types.Message, state: FSMContext):
    global my_ides
    if str(message.text) == str((await state.get_data())['auth']):
        my_ides.append(message.from_user.id)
        await state.update_data(mode=True)
        await start(message, state)
    else:
        await message.answer("Access denied from unauthorized users, bye!")


async def app(message: types.Message, state: FSMContext):
    await state.update_data(test=test_gen())
    keyboard = types.InlineKeyboardMarkup(row_width=2)
    buttons = [
        types.InlineKeyboardButton(text=(await state.get_data())['test'][1][0].title(), callback_data="A"),
        types.InlineKeyboardButton(text=(await state.get_data())['test'][1][1].title(), callback_data="B"),
        types.InlineKeyboardButton(text=(await state.get_data())['test'][1][2].title(), callback_data="C"),
        types.InlineKeyboardButton(text=(await state.get_data())['test'][1][3].title(), callback_data="D")]
    keyboard.add(*buttons)
    await message.answer(f'What means "{(await state.get_data())["test"][0].title()}" from italian', reply_markup=keyboard)


@dp.callback_query_handler(text="T", state=Status.start_state)
async def option_a(call: types.CallbackQuery, state: FSMContext):
    await app(call.message, state)
    await state.set_state(Status.test_state.state)


@dp.callback_query_handler(text="S", state=Status.start_state)
async def search(call: types.CallbackQuery):
    await call.message.answer("Enter word you want to search!")


@dp.callback_query_handler(text="A", state=Status.test_state)
async def option_a(call: types.CallbackQuery, state: FSMContext):
    if (await state.get_data())['test'][1][0] == data[(await state.get_data())['test'][0]]:
        await call.message.answer("✅Correct!")
    else:
        await call.message.answer("🚫Incorrect!")
    await call.answer(text=f"⏳Correct answer: {data[(await state.get_data())['test'][0]].title()}", show_alert=True)
    await sleep(2)
    await app(call.message, state)


@dp.callback_query_handler(text="B", state=Status.test_state)
async def option_b(call: types.CallbackQuery, state: FSMContext):
    if (await state.get_data())['test'][1][1] == data[(await state.get_data())['test'][0]]:
        await call.message.answer("✅Correct!")
    else:
        await call.message.answer("🚫Incorrect!")
    await call.answer(text=f"⏳Correct answer: {data[(await state.get_data())['test'][0]].title()}", show_alert=True)
    await sleep(2)
    await app(call.message, state)


@dp.callback_query_handler(text="C", state=Status.test_state)
async def option_c(call: types.CallbackQuery, state: FSMContext):
    if (await state.get_data())['test'][1][2] == data[(await state.get_data())['test'][0]]:
        await call.message.answer("✅Correct!")
    else:
        await call.message.answer("🚫Incorrect!")
    await call.answer(text=f"⏳Correct answer: {data[(await state.get_data())['test'][0]].title()}", show_alert=True)
    await sleep(2)
    await app(call.message, state)


@dp.callback_query_handler(text="D", state=Status.test_state)
async def option_d(call: types.CallbackQuery, state: FSMContext):
    if (await state.get_data())['test'][1][3] == data[(await state.get_data())['test'][0]]:
        await call.message.answer("✅Correct!")
    else:
        await call.message.answer("🚫Incorrect!")
    await call.answer(text=f"⏳Correct answer: {data[(await state.get_data())['test'][0]].title()}", show_alert=True)
    await sleep(2)
    await app(call.message, state)


def test_gen():
    test = [None, None, None]
    test[0] = choice([i for i in data.keys()])
    test[1] = option_gen(data[test[0]])
    return test


def option_gen(corr):
    out = [corr]
    val = [i for i in data.values()]
    for i in range(3):
        out.append(val.pop(val.index(choice(val))))
    return randomizer(out)


def randomizer(ops):
    out = list()
    for i in range(len(ops)):
        out.append(ops.pop(ops.index(choice(ops))))
    return out


def get_key(val):
    return [key for key, value in data.items() if value == val]


data = {
    "cosa": "thing",
    "anno": "year",
    "uomo": "man",
    "giorno": "day",
    "volta": "time",
    "casa": "home",
    "parte": "part",
    "vita": "life",
    "tempo": "time",
    "donna": "woman",
    "mano": "hand",
    "occhio": "eye",
    "ora": "now",
    "signore": "Mr.",
    "paese": "country, town",
    "momento": "moment",
    "modo": "way",
    "mondo": "world",
    "parola": "word",
    "padre": "father",
    "punto": "point",
    "lavoro": "work",
    "stato": "state",
    "caso": "case",
    "citta": "city",
    "guerra": "war",
    "strada": "street",
    "figlio": "son",
    "notte": "night",
    "prova": "test",
    "campagna": "countryside",
    "fiore": "flower",
    "sala": "room, hall",
    "misura": "measure",
    "posizione": "position",
    "natura": "nature",
    "ufficio": "office",
    "specie": "species",
    "successo": "success",
    "zona": "area",
    "fuoco": "fire",
    "soldato": "soldier",
    "vista": "view",
    "liberta": "freedom",
    "risultato": "result",
    "importanza": "importance",
    "dubbio": "doubt",
    "ricerca": "research",
    "dio": "God",
    "figura": "figure",
    "piazza": "square",
    "questione": "question",
    "nemico": "enemy",
    "pena": "punishment",
    "motivo": "reason",
    "esperienza": "experience",
    "ricordo": "memory",
    "albero": "tree",
    "eccellenza": "excellence",
    "malattia": "disease",
    "scienza": "science",
    "funzione": "function",
    "conseguenza": "result",
    "parete": "wall",
    "dente": "tooth",
    "distanza": "distance",
    "gusto": "taste",
    "impressione": "impression",
    "istituto": "institute",
    "quadro": "painting",
    "attenzione": "attention",
    "autore": "author",
    "difficolta": "difficulty",
    "passione": "passion",
    "commissione": "commission",
    "dito": "finger",
    "inizio": "Start",
    "programma": "program",
    "spettacolo": "show",
    "titolo": "title",
    "comunicazione": "communication",
    "fenomeno": "phenomenon",
    "maggio": "May",
    "stampa": "press",
    "denaro": "money",
    "destino": "destiny",
    "dovere": "must, duty",
    "faccia": "face",
    "moglie": "wife",
    "ragazzo": "boy",
    "bisogno": "need",
    "cielo": "sky",
    "letto": "bed",
    "fronte": "front",
    "conto": "bill",
    "corpo": "body",
    "numero": "number",
    "ministro": "minister",
    "problema": "problem",
    "chiesa": "church",
    "braccio": "arm",
    "bambino": "child",
    "pensiero": "thought",
    "pace": "peace",
    "morte": "death",
    "fine": "end",
    "forma": "form",
    "resto": "rest",
    "popolo": "people",
    "societa": "society",
    "studio": "study",
    "legge": "law",
    "libro": "book",
    "figlia": "daughter",
    "luogo": "place",
    "capello": "hair",
    "regione": "region",
    "monte": "mountain",
    "universita": "university",
    "treno": "train",
    "inverno": "winter",
    "nazione": "nation",
    "pagina": "page",
    "scopo": "purpose",
    "compagno": "partner",
    "necessita": "need",
    "potere": "power, can",
    "musica": "music",
    "dottore": "doctor",
    "sentimento": "feeling",
    "nave": "ship",
    "pietra": "stone",
    "produzione": "production",
    "speranza": "hope",
    "dolore": "ache",
    "carne": "meat",
    "proposito": "purpose",
    "elemento": "element",
    "stazione": "railway station",
    "materia": "matter",
    "scala": "ladder",
    "maniera": "way",
    "arma": "weapon",
    "fatica": "fatigue",
    "odore": "smell",
    "articolo": "article",
    "costruzione": "construction",
    "rivoluzione": "revolution",
    "zia": "aunt",
    "confronto": "comparison",
    "potenza": "power",
    "sforzo": "effort",
    "sicurezza": "safety",
    "crisi": "crisis",
    "cucina": "kitchen",
    "gatto": "cat",
    "pieta": "pity",
    "territorio": "territory",
    "attimo": "moment",
    "civilta": "civilization",
    "contatto": "contact",
    "errore": "error",
    "fretta": "hurry",
    "intenzione": "intention",
    "cultura": "culture",
    "giudizio": "judgement",
    "spesa": "expense",
    "aiuto": "help",
    "ambiente": "environment",
    "animo": "mind",
    "bestia": "beast",
    "signorina": "young lady",
    "ombra": "shadow",
    "azione": "action",
    "vento": "wind",
    "mattina": "morning",
    "colore": "color",
    "presidente": "president",
    "consiglio": "Advice",
    "principe": "prince",
    "viaggio": "travel",
    "genere": "kind",
    "giornale": "newspaper",
    "spirito": "spirit",
    "cavallo": "horse",
    "muro": "Wall",
    "situazione": "situation",
    "linea": "line",
    "giro": "round",
    "automobile": "car",
    "atto": "act",
    "aspetto": "appearance",
    "eta": "age",
    "fortuna": "luck",
    "oro": "gold",
    "partito": "party",
    "macchina": "machine",
    "carta": "paper",
    "minuto": "minute",
    "tratto": "stretch",
    "serie": "series",
    "visita": "visit",
    "coraggio": "courage",
    "direttore": "director",
    "esercito": "army",
    "grado": "degree",
    "padrone": "master",
    "risposta": "reply",
    "tavola": "table",
    "immagine": "image",
    "montagna": "mountain",
    "energia": "power",
    "fede": "wedding ring",
    "pane": "bread",
    "seguito": "following",
    "estate": "summer",
    "film": "movie",
    "frutto": "fruit",
    "onore": "honor",
    "pericolo": "danger",
    "scrittore": "writer",
    "collina": "hill",
    "zio": "uncle",
    "difesa": "defence",
    "metro": "meter",
    "collo": "neck",
    "cura": "care",
    "disposizione": "layout",
    "Domenica": "Sunday",
    "calcio": "football",
    "fantasia": "fantasy",
    "matrimonio": "marriage",
    "medico": "doctor",
    "ospedale": "Hospital",
    "pianura": "flat land",
    "tavolo": "table",
    "fame": "hunger",
    "latte": "milk",
    "merito": "merit",
    "attore": "actor",
    "ricchezza": "wealth",
    "sacrificio": "sacrifice",
    "atteggiamento": "attitude",
    "concetto": "concept",
    "mestiere": "craft",
    "attesa": "waiting",
    "bagno": "bathroom",
    "foglia": "leaf",
    "istante": "instant",
    "lago": "lake",
    "questo": "this",
    "quello": "one",
    "piu": "more",
    "tutto": "all",
    "suo": "his",
    "altro": "other",
    "mio": "my",
    "quale": "which",
    "tanto": "much",
    "grande": "great",
    "poco": "little",
    "molto": "very",
    "nostro": "our",
    "stesso": "same",
    "primo": "first",
    "loro": "their",
    "ogni": "every",
    "proprio": "own",
    "solo": "only",
    "quanto": "how much",
    "bello": "beautiful",
    "qualche": "some",
    "nuovo": "new",
    "certo": "of course",
    "vero": "true",
    "buono": "good",
    "tuo": "your",
    "nessuno": "nobody",
    "alcuno": "any",
    "sereno": "serene",
    "puro": "pure",
    "normale": "normal",
    "perfetto": "perfect",
    "piano": "plan",
    "caratteristico": "characteristic",
    "russo": "Russian",
    "continuo": "continuous",
    "stupido": "stupid",
    "estremo": "extreme",
    "grigio": "Grey",
    "reale": "real",
    "interessante": "Interesting",
    "medesimo": "same",
    "religioso": "religious",
    "ampio": "large",
    "biondo": "blond",
    "ufficiale": "official",
    "attento": "careful",
    "enorme": "huge",
    "sottile": "thin",
    "triste": "sad",
    "minimo": "minimum",
    "privato": "private",
    "rapido": "rapid",
    "quarto": "fourth",
    "diretto": "direct",
    "nobile": "noble",
    "pericoloso": "dangerous",
    "economico": "cheap",
    "felice": "happy",
    "difficile": "difficult",
    "tedesco": "German",
    "breve": "short",
    "pronto": "ready",
    "serio": "serious",
    "presente": "here I'm",
    "migliore": "best",
    "facile": "easy",
    "terzo": "third",
    "caldo": "hot",
    "estero": "abroad",
    "largo": "wide",
    "pricipale": "pricipale",
    "verde": "green",
    "romano": "Roman",
    "umano": "human",
    "inutile": "useless",
    "moderno": "modern",
    "numeroso": "numerous",
    "simile": "similar",
    "fresco": "fresh",
    "militare": "military",
    "americano": "American",
    "vuoto": "empty",
    "ciascuno": "each",
    "tranquillo": "quiet",
    "contento": "happy",
    "sinistro": "left",
    "duro": "hard",
    "stanco": "tired",
    "azzurro": "light blue",
    "recente": "recent",
    "notevole": "remarkable",
    "cittadino": "citizen",
    "destro": "right",
    "europeo": "European",
    "zitto": "quiet",
    "medio": "average",
    "qualunque": "whatever",
    "straordinario": "extraordinary",
    "nudo": "naked",
    "futuro": "future",
    "cattolico": "Catholic",
    "capace": "able",
    "industriale": "industrial",
    "personale": "staff",
    "centrale": "central",
    "tecnico": "technical",
    "dolce": "sweet",
    "leggero": "light",
    "morale": "moral",
    "utile": "helpful",
    "contrario": "contrary",
    "speciale": "special",
    "peggio": "worse",
    "minore": "lower",
    "contadino": "farmer",
    "essere": "to be",
    "avere": "to have",
    "dire": "to say",
    "volere": "want",
    "sapere": "to know",
    "stare": "to stay",
    "vedere": "to see",
    "andare": "to go",
    "venire": "to come",
    "dare": "to give",
    "parlare": "to speak",
    "trovare": "to find",
    "sentire": "to feel, to hear",
    "lasciare": "to leave",
    "prendere": "to take",
    "guardare": "to look",
    "mettere": "to put",
    "pensare": "to think",
    "passare": "to pass",
    "credere": "to believe",
    "portare": "to bring",
    "parere": "to seem",
    "tornare": "to return",
    "sembrare": "to seem, to look like",
    "tenere": "to keep",
    "capire": "to understand",
    "morire": "to die",
    "camminare": "to walk",
    "ritrovare": "to find again",
    "durare": "to last",
    "accendere": "to turn on",
    "evitare": "to avoid",
    "immaginare": "to imagine",
    "ridurre": "to reduce",
    "contenere": "to contain",
    "fissare": "to fix",
    "costringere": "to force",
    "abbandonare": "to abandon",
    "attendere": "to wait for",
    "preferire": "to prefer",
    "scegliere": "to choose",
    "avvertire": "to warn",
    "proporre": "to propose",
    "temere": "to fear",
    "esprimere": "to express",
    "spingere": "to push",
    "salutare": "to greet",
    "udire": "to hear",
    "difendere": "to stick up for",
    "dirigere": "to direct",
    "cantare": "to sing",
    "sorgere": "to rise",
    "assicurare": "to ensure",
    "assumere": "to hire",
    "tendere": "to tend",
    "dividere": "to divide",
    "servire": "to serve",
    "giungere": "to reach",
    "fermare": "to stop",
    "apparire": "to appear",
    "amare": "to love",
    "esistere": "to exist",
    "intendere": "to hear",
    "salire": "to go up",
    "mancare": "to miss",
    "ridere": "to laugh",
    "lavorare": "to work",
    "alzare": "to raise up",
    "riconoscere": "to recognize",
    "sedere": "to sit down",
    "leggere": "to read",
    "cadere": "to fall",
    "mangiare": "to eat",
    "dormire": "to sleep",
    "raggiungere": "to reach",
    "comprendere": "to understand",
    "scendere": "to alight",
    "compiere": "to fulfill",
    "toccare": "to touch",
    "considerare": "to consider",
    "muovere": "to move",
    "stringere": "to tighten",
    "mandare": "to send",
    "domandare": "to ask",
    "ascoltare": "to listen",
    "vendere": "to sell",
    "distinguere": "to distinguish",
    "offendere": "to offend",
    "rimettere": "to return",
    "rompere": "to break",
    "godere": "to enjoy",
    "imporre": "to impose",
    "significare": "to mean",
    "desiderare": "to desire",
    "divertire": "to amuse",
    "volgere": "to turn",
    "giudicare": "to judge",
    "produrre": "to produce",
    "avvicinare": "to approach",
    "diffondere": "to spread",
    "ordinare": "to sort",
    "invitare": "to invite",
    "discutere": "to discuss",
    "sbagliare": "to make a mistake",
    "badare": "to look after",
    "tagliare": "to cut",
    "pubblicare": "to publish",
    "attaccare": "to attack",
    "imparare": "to learn",
    "prevedere": "to forecast",
    "scappare": "to run away",
    "spegnere": "to switch off",
    "annunciare": "to announce",
    "baciare": "to kiss",
    "formare": "to form",
    "uccidere": "to kill",
    "tirare": "to pull",
    "togliere": "to remove",
    "notare": "to notice",
    "aggiungere": "to add",
    "succedere": "to happen",
    "pagare": "to pay",
    "tentare": "to attempt",
    "accadere": "to happen",
    "creare": "to create",
    "importare": "to import",
    "pesare": "to weigh",
    "usare": "to use",
    "accettare": "to accept",
    "indicare": "to indicate",
    "buttare": "to throw",
    "battere": "to beat",
    "interessare": "to interest",
    "sorridere": "to smile",
    "condurre": "to conduct",
    "disporre": "to have",
    "unire": "to merge",
    "aiutare": "to help",
    "piangere": "to cry",
    "girare": "to turn",
    "levare": "to lift",
    "soffrire": "to suffer",
    "recare": "to cause",
    "confessare": "to confess",
    "arrestare": "to stop",
    "ringraziare": "to thank",
    "riunire": "to gather",
    "volare": "to fly",
    "fondare": "to found",
    "guidare": "to drive",
    "ferire": "to hurt",
    "opporre": "to oppose",
    "procedere": "to proceed",
    "smettere": "to stop",
    "consentire": "to allow",
    "innamorarsi": "to fall in love",
    "organizzare": "to organize",
    "rifiutare": "to reject",
    "riportare": "to report",
    "dipendere": "to depend",
    "provvedere": "to provide",
    "trascinare": "to drag",
    "fumare": "to smoke",
    "scoppiare": "to burst",
    "sognare": "to dream",
    "appoggiare": "to support",
    "armare": "to arm",
    "celebrare": "to celebrate",
    "descrivere": "to describe",
    "resistere": "to resist",
    "bruciare": "to burn",
    "colpire": "to hit",
    "il": "the",
    "di": "of",
    "e": "is",
    "a": "to",
    "un": "a",
    "in": "in",
    "che": "that",
    "non": "not",
    "si": "Yes, Yup",
    "da": "from",
    "lo": "the",
    "per": "for",
    "con": "with",
    "ma": "but",
    "come": "how",
    "su": "up",
    "mi": "me",
    "anche": "also",
    "o": "or",
    "io": "I",
    "se": "self",
    "perche": "because",
    "li": "there",
    "ci": "us",
    "ne": "neither",
    "lei": "she",
    "ancora": "yet",
    "tu": "you",
    "lui": "he",
    "esso": "it",
    "la": "there",
    "pero": "However",
    "subito": "immediately",
    "verso": "towards",
    "ecco": "here",
    "essa": "it",
    "fuori": "outside",
    "meno": "less",
    "adesso": "now",
    "niente": "nothing",
    "cioe": "that is",
    "male": "bad",
    "nulla": "nothing",
    "ah": "ha",
    "oh": "Oh",
    "quindi": "then",
    "appena": "as soon as",
    "insieme": "together",
    "dunque": "therefore",
    "dentro": "inside",
    "durante": "during",
    "almeno": "at least",
    "secondo": "second",
    "anzi": "rather",
    "oramai": "now",
    "tardi": "late",
    "insomma": "in conclusion",
    "presso": "At",
    "intanto": "in the meantime",
    "neanche": "neither",
    "piuttosto": "Rather",
    "stasera": "tonight",
    "percio": "therefore",
    "naturalmente": "of course",
    "accanto": "next",
    "eppure": "but yet",
    "eccetera": "etc",
    "finalmente": "finally",
    "infine": "finally",
    "poiche": "as",
    "comunque": "However",
    "dinanzi": "before",
    "abbastanza": "enough",
    "peccato": "sin",
    "certamente": "of course",
    "coloro": "they",
    "attorno": "about",
    "magari": "maybe",
    "oppure": "or",
    "inoltre": "Moreover",
    "indietro": "back",
    "addosso": "on",
    "addirittura": "even",
    "voce": "voice",
    "nome": "name",
    "sera": "evening",
    "acqua": "water",
    "amico": "friend",
    "fatto": "done",
    "gente": "people",
    "amore": "love",
    "storia": "history",
    "aria": "air",
    "forza": "power",
    "testa": "head",
    "ragione": "reason",
    "mare": "sea",
    "mese": "month",
    "capo": "head",
    "luce": "light",
    "sole": "Sun",
    "famiglia": "family",
    "piede": "foot",
    "persona": "person",
    "via": "street",
    "signora": "Mrs",
    "governo": "government",
    "senso": "sense",
    "opera": "Opera",
    "prodotto": "product",
    "festa": "party",
    "gioco": "game",
    "politica": "policy",
    "processo": "process",
    "vino": "wine",
    "porta": "door",
    "sud": "south",
    "sogno": "dream",
    "cane": "dog",
    "isola": "island",
    "movimento": "movement",
    "mente": "mind",
    "occasione": "opportunity",
    "prezzo": "price",
    "causa": "cause",
    "periodo": "period",
    "sviluppo": "development",
    "sorella": "sister",
    "effetto": "effect",
    "giardino": "garden",
    "attivita": "activities",
    "volonta": "will",
    "volto": "face",
    "base": "basis",
    "carattere": "character",
    "coscienza": "consciousness",
    "guardia": "guard",
    "memoria": "memory",
    "terreno": "ground",
    "animale": "animal",
    "direzione": "direction",
    "ferro": "iron",
    "punta": "tip",
    "regno": "kingdom",
    "epoca": "era",
    "luna": "moon",
    "provincia": "province",
    "voglia": "wish",
    "differenza": "difference",
    "controllo": "control",
    "grazia": "grace",
    "passato": "past",
    "spazio": "space",
    "stella": "star",
    "corsa": "race",
    "erba": "grass",
    "massa": "mass",
    "origine": "origin",
    "polizia": "police",
    "soluzione": "solution",
    "chilometro": "kilometer",
    "madre": "mother",
    "paura": "fear",
    "cuore": "heart",
    "idea": "idea",
    "fondo": "background",
    "esempio": "example",
    "ordine": "order",
    "posto": "place",
    "campo": "field",
    "condizione": "condition",
    "professore": "teacher",
    "marito": "husband",
    "verita": "truth",
    "segno": "sign",
    "diritto": "right",
    "lettera": "letter",
    "ragazza": "girl",
    "scuola": "school",
    "camera": "room",
    "gruppo": "group",
    "discorso": "speech",
    "centro": "center",
    "secolo": "century",
    "mezzo": "half",
    "tipo": "guy",
    "colpa": "fault",
    "rispetto": "respect",
    "scena": "scene",
    "oggetto": "object",
    "possibilita": "possibility",
    "mamma": "mom",
    "presenza": "presence",
    "teatro": "theater",
    "caffe": "coffee",
    "principio": "principle",
    "termine": "term",
    "lingua": "tongue",
    "pezzo": "piece",
    "autorita": "authority",
    "gamba": "leg",
    "patria": "homeland",
    "albergo": "hotel",
    "gioia": "joy",
    "argomento": "topic",
    "sguardo": "look",
    "relazione": "report",
    "classe": "class",
    "battaglia": "battle",
    "viso": "face",
    "gesto": "gesture",
    "mattino": "morning",
    "opinione": "opinion",
    "ponte": "bridge",
    "sorriso": "smile",
    "frase": "phrase",
    "limite": "limit",
    "ritorno": "return",
    "bosco": "wood",
    "esame": "exam",
    "lato": "side",
    "operazione": "operation",
    "pranzo": "lunch",
    "costa": "it costs",
    "prato": "meadow",
    "repubblica": "republic",
    "valle": "valley",
    "nord": "north",
    "cortile": "courtyard",
    "pelle": "skin",
    "proposta": "proposal",
    "riva": "shore",
    "segretario": "secretary",
    "abito": "dress",
    "chiave": "key",
    "corrente": "current",
    "operaio": "worker",
    "corso": "course",
    "finestra": "window",
    "arte": "art",
    "sistema": "system",
    "bocca": "mouth",
    "anima": "soul",
    "palazzo": "palace",
    "passo": "step",
    "giornata": "day",
    "servizio": "service",
    "rapporto": "relationship",
    "milione": "million",
    "stanza": "room",
    "valore": "value",
    "colpo": "blow",
    "sangue": "blood",
    "interesse": "interest",
    "spalla": "shoulder",
    "silenzio": "silence",
    "settimana": "week",
    "notizia": "news",
    "fratello": "brother",
    "realta": "reality",
    "industria": "industry",
    "piacere": "pleasure, to like",
    "maestro": "master",
    "personaggio": "character",
    "pomeriggio": "afternoon",
    "fianco": "side",
    "bambina": "child",
    "bellezza": "beauty",
    "domanda": "question",
    "pianta": "plant",
    "sede": "seat",
    "affare": "deal",
    "bene": "well",
    "meta": "half",
    "papa": "Pope",
    "fiume": "river",
    "lotta": "fight",
    "mercato": "market",
    "angolo": "angle",
    "compagnia": "company",
    "espressione": "expression",
    "labbro": "lip",
    "villa": "villa",
    "desiderio": "desire",
    "giovanotto": "young man",
    "poeta": "poet",
    "stagione": "season",
    "peso": "weight",
    "tono": "tone",
    "croce": "cross",
    "decisione": "decision",
    "poesia": "poetry",
    "fiducia": "confidence",
    "filo": "wire",
    "folla": "crowd",
    "qualita": "quality",
    "roba": "stuff",
    "conoscenza": "knowledge",
    "favore": "favor",
    "popolazione": "population",
    "strumento": "tool",
    "uso": "use",
    "vestito": "dress",
    "commercio": "business",
    "fabbrica": "factory",
    "giugno": "June",
    "giustizia": "justice",
    "avvocato": "lawyer",
    "messa": "mass",
    "orecchio": "ear",
    "sonno": "sleep",
    "congresso": "congress",
    "porto": "port",
    "italiano": "Italian",
    "ultimo": "last",
    "vecchio": "old",
    "piccolo": "small",
    "troppo": "too much",
    "tale": "such",
    "giovane": "young",
    "alto": "tall",
    "vostro": "your",
    "diverso": "different",
    "meglio": "better",
    "lungo": "long",
    "povero": "poor",
    "maggiore": "greater",
    "lontano": "far",
    "vicino": "close",
    "possibile": "possible",
    "caro": "Dear",
    "pieno": "full",
    "nero": "black",
    "particolare": "particular",
    "bianco": "White",
    "forte": "strong",
    "politico": "politic",
    "attuale": "current",
    "latino": "Latin",
    "impossibile": "impossible",
    "giallo": "yellow",
    "pazzo": "crazy",
    "sacro": "sacred",
    "comodo": "comfortable",
    "elettrico": "electric",
    "assoluto": "absolute",
    "cristiano": "Christian",
    "antico": "ancient",
    "rosso": "red",
    "chiaro": "clear",
    "unico": "single",
    "sicuro": "sure",
    "importante": "important",
    "vario": "varied",
    "giusto": "quite right",
    "francese": "French",
    "vivo": "I live",
    "generale": "general",
    "ricco": "rich",
    "grosso": "big",
    "necessario": "necessary",
    "libero": "free",
    "nazionale": "national",
    "basso": "bass",
    "semplice": "simple",
    "grave": "serious",
    "pubblico": "public",
    "comune": "common",
    "freddo": "cold",
    "storico": "historical",
    "superiore": "higher",
    "inglese": "English",
    "fermo": "stationary",
    "solito": "usual",
    "buio": "dark",
    "strano": "strange",
    "noto": "known",
    "prossimo": "next one",
    "profondo": "deep",
    "sociale": "social",
    "cattivo": "bad",
    "massimo": "maximum",
    "intero": "full",
    "uguale": "equal",
    "bravo": "good boy",
    "brutto": "ugly",
    "preciso": "accurate",
    "qualsiasi": "any",
    "improvviso": "sudden",
    "famoso": "famous",
    "straniero": "foreigner",
    "civile": "civil",
    "internazionale": "international",
    "interno": "internal",
    "vasto": "extensive",
    "segreto": "secret",
    "greco": "Greek",
    "naturale": "natural",
    "chiamare": "to call",
    "conoscere": "to know",
    "rimanere": "to stay",
    "chiedere": "to ask",
    "cercare": "to search for",
    "entrare": "to come in",
    "vivere": "to live",
    "aprire": "to open",
    "uscire": "to go out",
    "ricordare": "to remember",
    "bisognare": "need",
    "cominciare": "to begin",
    "rispondere": "to answer, to reply",
    "aspettare": "to wait",
    "riuscire": "to succeed",
    "chiudere": "to close",
    "finire": "to finish",
    "arrivare": "to arrive",
    "scrivere": "to write",
    "diventare": "to become",
    "restare": "to remain",
    "seguire": "to follow",
    "bastare": "to suffice",
    "perdere": "to lose",
    "rendere": "to make (big, small..)",
    "correre": "to run",
    "salvare": "to save",
    "vestire": "to dress",
    "costruire": "to build",
    "scusare": "to excuse",
    "mantenere": "to maintain",
    "ritenere": "to consider",
    "concludere": "to conclude",
    "saltare": "to jump",
    "stabilire": "to establish",
    "appartenere": "to belong",
    "possedere": "to possess",
    "risultare": "to result",
    "suonare": "to play",
    "coprire": "to cover up",
    "insegnare": "to teach",
    "affermare": "to assert",
    "rivelare": "to reveal",
    "conservare": "to preserve",
    "risolvere": "to solve",
    "concedere": "to grant",
    "limitare": "to limit",
    "abitare": "to live",
    "convincere": "to convince",
    "comprare": "to buy",
    "legare": "to tie",
    "sostenere": "to sustain",
    "nascere": "to be born",
    "presentare": "to introduce",
    "trattare": "to deal",
    "continuare": "to continue",
    "partire": "to leave",
    "decidere": "to decide",
    "ricevere": "to receive",
    "osservare": "to observe",
    "permettere": "to allow",
    "avvenire": "to occur",
    "spiegare": "to explain",
    "raccogliere": "to collect",
    "ottenere": "to obtain",
    "offrire": "to offer",
    "mostrare": "to exhibit",
    "accompagnare": "to accompany",
    "dimenticare": "to forget",
    "pregare": "to pray",
    "raccontare": "to tell",
    "bere": "to drinking",
    "ritornare": "to return",
    "cambiare": "to change",
    "dimostrare": "to demonstrate",
    "sperare": "to hope",
    "sposare": "to marry",
    "ammettere": "to admit",
    "fuggire": "to run away",
    "liberare": "to free",
    "riferire": "to report",
    "svegliare": "to wake up",
    "capitare": "to happen",
    "posare": "to place",
    "impedire": "to prevent",
    "gettare": "to throw",
    "esporre": "to expose",
    "attraversare": "go across",
    "fornire": "to provide",
    "segnare": "to mark",
    "superare": "to overcome",
    "rivedere": "to review",
    "allontanare": "to remove",
    "ammazzare": "to kill",
    "accogliere": "to receive",
    "voltare": "to turn",
    "preoccupare": "to worry",
    "provocare": "to cause",
    "riempire": "to fill",
    "partecipare": "to take part",
    "piantare": "to plant",
    "rientrare": "to re-enter",
    "richiedere": "to request",
    "nascondere": "to hide",
    "ripetere": "to repeat",
    "scoprire": "to discover",
    "preparare": "prepare",
    "scorrere": "to slide",
    "rappresentare": "to represent",
    "riprendere": "to resume",
    "costituire": "to constitute",
    "incontrare": "to meet",
    "valere": "be worth",
    "accorgersi": "to notice",
    "provare": "to try",
    "riguardare": "to concern",
    "rivolgere": "to turn",
    "tacere": "to be silent",
    "occorrere": "to take",
    "porre": "to place",
    "vincere": "to win",
    "svolgere": "to perform",
    "studiare": "to study",
    "crescere": "to grow up",
    "divenire": "to become",
    "gridare": "to shout",
    "dichiarare": "to declare",
    "contare": "to count",
    "giocare": "to play",
    "assistere": "to assist",
    "aumentare": "to increase",
    "lanciare": "to launch",
    "determinare": "to determine",
    "scherzare": "to joke",
    "elevare": "to raise",
    "promettere": "to promise",
    "scomparire": "to disappear",
    "trarre": "to draw",
    "distruggere": "to destroy",
    "meritare": "to deserve",
    "dedicare": "to devote",
    "iniziare": "to start",
    "sorprendere": "to surprise",
    "trasformare": "to commute",
    "estendere": "to extend",
    "staccare": "to remove",
    "affrontare": "to face up to",
    "avanzare": "to push forward",
    "comporre": "to compose",
    "escludere": "to exclude",
    "figurare": "to appear",
    "insistere": "to insist",
    "senza": "without",
    "cui": "which",
    "chi": "who",
    "gia": "already",
    "dopo": "after",
    "uno": "one",
    "noi": "we",
    "dove": "where",
    "qui": "here",
    "no": "no",
    "allora": "then",
    "tra": "between",
    "vi": "you",
    "fra": "between",
    "prima": "before",
    "forse": "perhaps",
    "sotto": "under",
    "voi": "you",
    "fino": "till",
    "oggi": "today",
    "quasi": "almost",
    "pure": "also",
    "egli": "he",
    "mentre": "while",
    "contro": "versus",
    "invece": "instead",
    "oltre": "over",
    "intorno": "around",
    "sopra": "above",
    "dietro": "behind",
    "davanti": "in front of",
    "soltanto": "only",
    "infatti": "indeed",
    "qualcosa": "something",
    "spesso": "often",
    "accordo": "agreement",
    "ieri": "yesterday",
    "davvero": "really",
    "qualcuno": "someone",
    "avanti": "come on",
    "assai": "very",
    "presto": "soon",
    "qua": "here",
    "domani": "tomorrow",
    "circa": "about",
    "giu": "down",
    "soprattutto": "mostly",
    "nemmeno": "not even",
    "grazie": "thank you",
    "tuttavia": "however",
    "appunto": "just",
    "neppure": "neither",
    "eh": "huh",
    "veramente": "really",
    "finche": "as long as",
    "perfino": "even",
    "affatto": "at all",
    "stamattina": "This morning",
    "completamente": "completely",
    "probabilmente": "probably",
    "chissa": "who knows",
    "ognuno": "each one",
    "entro": "within",
}

if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)
